'use client';
import { Timestamp } from 'firebase/firestore';
import type { Task, PublicProfile, Note, StudyGroup, Transaction } from '@/lib/types';

export const mockTasks: Task[] = [
    {
      id: 'task-1',
      creatorId: 'user-2',
      creatorName: 'Jane Doe',
      creatorAvatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Jane%20Doe',
      category: 'Writing',
      description: 'Need help proofreading my history essay on the Roman Empire. It is about 5 pages long.',
      durationHours: 2,
      status: 'open',
      location: 'Online',
      createdAt: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 2)), // 2 hours ago
    },
    {
      id: 'task-2',
      creatorId: 'user-3',
      creatorName: 'Peter Jones',
      creatorAvatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Peter%20Jones',
      category: 'Tech',
      description: 'My laptop is running slow, looking for someone to help me diagnose the issue.',
      durationHours: 1,
      status: 'open',
      location: 'Campus IT Center',
      createdAt: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 24)), // 1 day ago
    },
    {
      id: 'task-3',
      creatorId: 'user-4',
      creatorName: 'Maria Garcia',
      creatorAvatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Maria%20Garcia',
      category: 'Tutoring',
      description: 'Struggling with Calculus II concepts, specifically integration by parts. Need a tutor for a 1-hour session.',
      durationHours: 1,
      status: 'open',
      location: 'Library, 2nd Floor',
      createdAt: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 5)), // 5 hours ago
    },
    {
      id: 'task-4',
      creatorId: 'user-5',
      creatorName: 'Chris Lee',
      creatorAvatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Chris%20Lee',
      category: 'Design',
      description: 'Looking for feedback on a logo I designed for a club. Quick 30-minute review.',
      durationHours: 1,
      status: 'open',
      location: 'Online',
      createdAt: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 8)), // 8 hours ago
    },
    {
      id: 'task-5',
      creatorId: 'user-6',
      creatorName: 'Patricia Williams',
      creatorAvatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Patricia%20Williams',
      category: 'Music',
      description: 'Need a guitar player to practice a duet for an upcoming performance. About 1.5 hours.',
      durationHours: 2,
      status: 'open',
      location: 'Music Building, Room 3',
      createdAt: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 48)), // 2 days ago
    },
    {
        id: 'task-6',
        creatorId: 'user-7',
        creatorName: 'Michael Brown',
        creatorAvatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Michael%20Brown',
        category: 'Photography',
        description: 'Need a model for a portrait photography project. No experience necessary. 2 hours.',
        durationHours: 2,
        status: 'open',
        location: 'Campus Quad',
        createdAt: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 30)), // 30 hours ago
    }
  ];

export const mockProfiles: PublicProfile[] = [
    {
        id: 'user-2',
        name: 'Alex Johnson',
        bio: 'Computer Science major passionate about open-source and web development. Loves hiking on weekends.',
        skills: ['JavaScript', 'React', 'Node.js', 'Python', 'Firebase'],
        rating: 4.8,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Alex%20Johnson',
        timeBalance: 125,
    },
    {
        id: 'user-3',
        name: 'Samantha Lee',
        bio: 'Graphic Design student with a knack for creating beautiful and intuitive user interfaces.',
        skills: ['UI/UX Design', 'Figma', 'Adobe XD', 'Illustration'],
        rating: 4.9,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Samantha%20Lee',
        timeBalance: 88,
    },
    {
        id: 'user-4',
        name: 'David Chen',
        bio: 'Medical student, enjoys helping others with biology and chemistry concepts. Also a great public speaker.',
        skills: ['Biology', 'Chemistry', 'Public Speaking', 'MCAT Prep'],
        rating: 4.7,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=David%20Chen',
        timeBalance: 210,
    },
    {
        id: 'user-5',
        name: 'Laura Williams',
        bio: 'Full-stack developer specializing in the MERN stack.',
        skills: ['React', 'Node.js', 'TypeScript', 'GraphQL', 'MongoDB'],
        rating: 4.9,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Laura%20Williams',
        timeBalance: 150,
    },
    {
        id: 'user-6',
        name: 'Ben Carter',
        bio: 'Backend engineer with expertise in enterprise Java applications.',
        skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Microservices', 'MongoDB'],
        rating: 4.8,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Ben%20Carter',
        timeBalance: 95,
    },
    {
        id: 'user-7',
        name: 'Olivia Martinez',
        bio: 'Frontend enthusiast who loves building fast and beautiful web apps.',
        skills: ['React', 'Next.js', 'Tailwind CSS', 'Vercel', 'Node.js'],
        rating: 4.9,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Olivia%20Martinez',
        timeBalance: 180,
    },
    {
        id: 'user-8',
        name: 'James Rodriguez',
        bio: 'Data scientist who also builds web apps with Python and React.',
        skills: ['Python', 'Django', 'React', 'MongoDB', 'AWS'],
        rating: 4.6,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=James%20Rodriguez',
        timeBalance: 70,
    },
    {
        id: 'user-9',
        name: 'Sophia Garcia',
        bio: 'Software engineer focused on scalable backend systems with Java and Spring.',
        skills: ['Java', 'Spring Boot', 'React', 'MySQL', 'Docker'],
        rating: 4.7,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Sophia%20Garcia',
        timeBalance: 110,
    },
    {
        id: 'user-10',
        name: 'Daniel Kim',
        bio: 'Real-time application developer using Node.js and WebSockets.',
        skills: ['Node.js', 'Express', 'MongoDB', 'React', 'Socket.IO'],
        rating: 4.8,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Daniel%20Kim',
        timeBalance: 130,
    },
    {
        id: 'user-11',
        name: 'Emily White',
        bio: 'Cloud-native developer with experience in multiple frameworks.',
        skills: ['Angular', 'Node.js', 'MongoDB', 'GCP', 'Spring Boot'],
        rating: 4.5,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Emily%20White',
        timeBalance: 60,
    },
    {
        id: 'user-12',
        name: 'Matthew Harris',
        bio: 'Mobile and backend developer building with Kotlin and Java.',
        skills: ['Java', 'Spring Boot', 'Kotlin', 'Android Dev', 'Firebase'],
        rating: 4.6,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Matthew%20Harris',
        timeBalance: 80,
    },
    {
        id: 'user-13',
        name: 'Ava Clark',
        bio: 'Specialist in building resilient, message-driven microservices.',
        skills: ['Spring Boot', 'Kafka', 'RabbitMQ', 'React', 'Microservices'],
        rating: 4.9,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Ava%20Clark',
        timeBalance: 190,
    },
    {
        id: 'user-14',
        name: 'William Brown',
        bio: 'Loves diving deep into how computers work from the metal up.',
        skills: ['C++', 'Operating Systems', 'Linux', 'Kernel Dev', 'Computer Architecture'],
        rating: 4.9,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=William%20Brown',
        timeBalance: 200,
    },
    {
        id: 'user-15',
        name: 'Isabella Wilson',
        bio: 'Competitive programmer who enjoys solving complex algorithmic puzzles.',
        skills: ['Python', 'Algorithms', 'Data Structures', 'DAA', 'Competitive Programming'],
        rating: 5.0,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Isabella%20Wilson',
        timeBalance: 250,
    },
    {
        id: 'user-16',
        name: 'Michael Miller',
        bio: 'Network engineer in training, fascinated by the internet\'s infrastructure.',
        skills: ['Computer Networks', 'Cisco', 'Wireshark', 'TCP/IP', 'OSI Model'],
        rating: 4.7,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Michael%20Miller',
        timeBalance: 115,
    },
    {
        id: 'user-17',
        name: 'Grace Taylor',
        bio: 'Hardware enthusiast building custom processors and learning OS design.',
        skills: ['Computer Architecture', 'Verilog', 'Assembly', 'RISC-V', 'Operating Systems'],
        rating: 4.8,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Grace%20Taylor',
        timeBalance: 145,
    },
    {
        id: 'user-18',
        name: 'Ethan Thomas',
        bio: 'Problem solver with a passion for efficient algorithms and clean code.',
        skills: ['Java', 'Algorithms', 'DAA', 'Dynamic Programming', 'Computer Networks'],
        rating: 4.9,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Ethan%20Thomas',
        timeBalance: 185,
    },
    {
        id: 'user-19',
        name: 'Chloe Moore',
        bio: 'Loves understanding concurrent systems and low-level programming.',
        skills: ['Operating Systems', 'Concurrency', 'C', 'Computer Architecture', 'DAA'],
        rating: 4.8,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Chloe%20Moore',
        timeBalance: 165,
    },
    {
        id: 'user-20',
        name: 'Jacob Anderson',
        bio: 'Cybersecurity student focusing on network security and ethical hacking.',
        skills: ['Computer Networks', 'Cybersecurity', 'Python', 'DAA', 'Operating Systems'],
        rating: 4.7,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Jacob%20Anderson',
        timeBalance: 105,
    },
    {
        id: 'user-21',
        name: 'Mia Jackson',
        bio: 'Future chip designer with a love for digital logic and processor design.',
        skills: ['Computer Architecture', 'Digital Logic', 'VHDL', 'DAA', 'Operating Systems'],
        rating: 4.9,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Mia%20Jackson',
        timeBalance: 175,
    },
    {
        id: 'user-22',
        name: 'Noah Martin',
        bio: 'Building the next generation of secure and scalable distributed systems.',
        skills: ['Computer Networks', 'Network Security', 'Go', 'Distributed Systems', 'Node.js'],
        rating: 4.8,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Noah%20Martin',
        timeBalance: 155,
    },
    {
        id: 'user-23',
        name: 'Abigail Lee',
        bio: 'Working on IoT projects and exploring wireless communication protocols.',
        skills: ['Computer Networks', 'Wireless Comms', 'Python', 'IoT', 'Embedded Systems'],
        rating: 4.6,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Abigail%20Lee',
        timeBalance: 85,
    },
    {
        id: 'user-24',
        name: 'Henry Gonzalez',
        bio: 'Designing and verifying complex digital circuits for modern hardware.',
        skills: ['VLSI', 'Cadence', 'Verilog', 'Digital Design', 'ECE'],
        rating: 4.9,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Henry%20Gonzalez',
        timeBalance: 220,
    },
    {
        id: 'user-25',
        name: 'Charlotte Perez',
        bio: 'Signal processing wizard who can clean up any noisy data you throw at her.',
        skills: ['Signal Processing', 'MATLAB', 'DSP', 'Image Processing', 'ECE'],
        rating: 5.0,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Charlotte%20Perez',
        timeBalance: 280,
    },
    {
        id: 'user-26',
        name: 'Lucas Sanchez',
        bio: 'Embedded systems hobbyist building cool gadgets with Arduino and RPi.',
        skills: ['Microcontrollers', 'Arduino', 'Raspberry Pi', 'Embedded C', 'ECE'],
        rating: 4.8,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Lucas%20Sanchez',
        timeBalance: 135,
    },
    {
        id: 'user-27',
        name: 'Amelia Rivera',
        bio: 'Analog circuit designer with a passion for precision and detail.',
        skills: ['Analog Circuits', 'PSpice', 'Electronics', 'VLSI', 'ECE'],
        rating: 4.7,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Amelia%20Rivera',
        timeBalance: 90,
    },
    {
        id: 'user-28',
        name: 'Elijah Torres',
        bio: 'Robotics and control systems engineer making machines move.',
        skills: ['Control Systems', 'MATLAB', 'Robotics', 'Signal Processing', 'ECE'],
        rating: 4.9,
        avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Elijah%20Torres',
        timeBalance: 195,
    }
];

export const mockNotes: Note[] = [
    {
        id: 'note-1',
        title: 'Complete Guide to React Hooks',
        uploaderId: 'user-2',
        uploaderName: 'Alex Johnson',
        subject: 'Computer Science',
        content: 'This note covers useState, useEffect, useContext, and custom hooks with detailed examples.',
        tags: ['react', 'javascript', 'frontend', 'webdev'],
        upvotes: 125,
        createdAt: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 48)),
    },
    {
        id: 'note-2',
        title: 'Organic Chemistry I - Reaction Mechanisms',
        uploaderId: 'user-4',
        uploaderName: 'David Chen',
        subject: 'CHEM 201',
        content: 'Summary of all key reaction mechanisms for the final exam, including SN1, SN2, E1, and E2.',
        tags: ['chemistry', 'organic', 'exam-prep'],
        upvotes: 88,
        createdAt: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 72)),
    },
    {
        id: 'note-3',
        title: 'Color Theory in UI Design',
        uploaderId: 'user-3',
        uploaderName: 'Samantha Lee',
        subject: 'Graphic Design',
        content: 'Principles of color theory and how to apply them to create visually appealing and accessible user interfaces.',
        tags: ['ui', 'ux', 'design', 'color-theory'],
        upvotes: 210,
        createdAt: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 24)),
    }
];

export const mockStudyGroups: StudyGroup[] = [
    {
        id: 'group-1',
        subject: 'Data Structures & Algorithms Final Prep',
        hostId: 'user-2',
        hostName: 'Alex Johnson',
        scheduledTime: Timestamp.fromDate(new Date(Date.now() + 3600 * 1000 * 24 * 2)),
        participantIds: ['user-2', 'user-3'],
        status: 'upcoming',
    },
    {
        id: 'group-2',
        subject: 'Live Figure Drawing Session',
        hostId: 'user-3',
        hostName: 'Samantha Lee',
        scheduledTime: Timestamp.fromDate(new Date(Date.now() + 3600 * 1000 * 3)),
        participantIds: ['user-3', 'user-4', 'user-1'],
        status: 'live',
    },
     {
        id: 'group-3',
        subject: 'MCAT Biology Review',
        hostId: 'user-4',
        hostName: 'David Chen',
        scheduledTime: Timestamp.fromDate(new Date(Date.now() + 3600 * 1000 * 24 * 5)),
        participantIds: ['user-4'],
        status: 'upcoming',
    }
];

export const mockTransactions: Omit<Transaction, 'participantIds'>[] = [
    {
        id: 'tx-1',
        helperId: 'user-2',
        helperName: 'Alex Johnson',
        seekerId: 'current-user-id',
        seekerName: 'Your Name',
        taskDescription: 'Help with React project',
        hoursTransferred: 3,
        timestamp: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 24 * 2)),
    },
    {
        id: 'tx-2',
        helperId: 'current-user-id',
        helperName: 'Your Name',
        seekerId: 'user-3',
        seekerName: 'Samantha Lee',
        taskDescription: 'Proofread English essay',
        hoursTransferred: 1,
        timestamp: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 24 * 5)),
    },
    {
        id: 'tx-3',
        helperId: 'current-user-id',
        helperName: 'Your Name',
        seekerId: 'user-4',
        seekerName: 'David Chen',
        taskDescription: 'Tutoring for Biology exam',
        hoursTransferred: 2,
        timestamp: Timestamp.fromDate(new Date(Date.now() - 3600 * 1000 * 24 * 10)),
    },
];
